// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmnzoijydogxwgevevvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptbnpvaWp5ZG9neHdnZXZldnZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1ODM5MDEsImV4cCI6MjA3MjE1OTkwMX0.a6hOB6w2psLjw_SvzfYfuQiIZpQSnJtp0yUux17IZbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});